name: Laravel Pint

on:
  push:
    branches:
      - main

jobs:
  laravel-pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.head_ref }}

      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: '8.4'
          php-extensions: 'json, dom, curl, libxml, mbstring'

      - name: Install Laravel Pint
        run: composer global require laravel/pint

      - name: Run Pint(Laravel Code style)
        run: pint

      - name: Commit Code Style Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@robot.com"
          git add .
          git commit -m "Code style fixed automatically by Laravel Pint" || exit 0
          git push
