name: PHPStan

on:
  push:
    branches:
      - main
    paths:
      - '**.php'
      - 'phpstan.neon'
      - '.github/workflows/phpstan.yml'
  pull_request:
    paths:
      - '**.php'
      - 'phpstan.neon'
      - '.github/workflows/phpstan.yml'

concurrency:
  group: phpstan-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: '8.4'

      - name: Install composer dependencies
        run: composer install -q --no-interaction --no-progress

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
