name: Pint

on:
  push:
    branches:
      - main
    paths:
      - '**.php'
      - '.github/workflows/pint.yml'
  pull_request:
    paths:
      - '**.php'
      - '.github/workflows/pint.yml'

concurrency:
  group: pint-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pint:
    name: pint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: '8.4'

      - name: Install composer dependencies
        run: composer install -q --no-interaction --no-progress

      - name: Run Pint
        run: vendor/bin/pint --test
